paths:
  dir_processed: "lab/data/processed"
  dir_artifacts_standard: "lab/artifacts/standard_classifier"
  dir_artifacts_dnn: "lab/artifacts/dnn"

mlflow_experiment: "kdl-project-template"

training:
  random_seed: 0
  n_workers: 2
  batch_size: 30
  epochs: 15
  lr: 0.0001

test:
  paths:
    dir_processed: "temp"
    dir_artifacts_standard: "lab/artifacts/standard_classifier"
    dir_artifacts_dnn: "lab/artifacts/dnn"

  mlflow_experiment:

  training:
    random_seed: 0
    n_workers: 1
    batch_size: 30
    epochs: 1
    lr: 0.0001
