name: kdl_environment
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
      - torch==1.12.1
      - mlflow==2.6.0
      - pandas==1.4.3
      - mock==5.0.1
      - scikit-learn==1.3.0
      - numpy==1.24.1
      - pynvml==11.5.0
      - matplotlib==3.6.2
      - boto3==1.24.59
      - azureml-core==1.48.0
      - azureml-mlflow==1.52.0
      - azure-ai-ml==1.10.0
      - azureml-sdk==1.48.0
      - python-dotenv==1.0.0
      - aiohttp
      - azure-storage-blob
