name: data_upload_environment
# version: 1
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
      - sklearn==0.0
      - mlflow==2.6.0
      - mock==5.0.1
      - torch==1.12.1
      - pynvml==11.5.0
      - matplotlib==3.6.2
      - boto3==1.24.59
      - azureml-mlflow==1.52.0
      - azureml-core==1.52.0
      - python-dotenv==1.0.0
      - aiohttp
