name: data_upload_environment
# version: 1
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
      - torch==1.12.1
      - pandas==1.4.3
      - scikit-learn==1.3.0
      - numpy==1.24.1
      - pynvml==11.5.0
      - azureml-core==1.48.0
      - azure-ai-ml==1.10.0
      - azureml-sdk==1.48.0
      - python-dotenv==1.0.0
      - azure-storage-blob==12.17.0
