name: Create pr
on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: "Name of experiment"
        required: true

run-name: "Create PR for experiment ${{ github.event.inputs.experiment_name }}"

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  PYTHONPATH: ${{ github.workspace }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MLFLOW_S3_ENDPOINT_URL: https://minio.kdl-dell.konstellation.io
  TODO: Change bucket name
  MLFLOW_URL: https://<project-name>-mlflow.kdl-dell.konstellation.io
  EXP_NAME: ${{ github.event.inputs.experiment_name }}
jobs:
  train-and-report:
    runs-on: ["igz", "dell", "cpu"]
    container:
      image: konstellation/kdl-py:3.9-1.5.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Pipenv setup
        run: |
          pipenv sync --system

      - name: Dvc setup
        run: |
          TODO: Add git repository
          git remote add experiments_adress https://oauth2:${{ env.REPO_TOKEN }}@github.com/<route to repository>

      - name: Create branch
        run: |
          dvc exp pull experiments_adress "${{ env.EXP_NAME }}"
          dvc exp branch "${{ env.EXP_NAME }}" "${{ env.EXP_NAME }}"
          git checkout "${{ env.EXP_NAME }}"

      - name: Pull raw data
        run: |
          dvc pull lab/data/raw --recursive

      - name: Reproduce Experiment ${{ env.EXP_NAME }}
        run: |
          dvc repro --pull

      - name: Create Pull Request
        run: |
          cml pr create . --targetBranch=main
