name: Create pr
on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: "Name of experiment"
        required: true

run-name: "Create PR for experiment ${{ github.event.inputs.experiment_name }}"

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  PYTHONPATH: ${{ github.workspace }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MLFLOW_S3_ENDPOINT_URL: https://minio.kdl-dell.konstellation.io
  TODO:
  MLFLOW_URL: https://<bucket-name>-mlflow.kdl-dell.konstellation.io

jobs:
  train-and-report:
    runs-on: ["igz", "dell", "cpu"]
    container:
      image: konstellation/kdl-py:3.9-1.5.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Pipenv setup
        run: |
          pipenv sync --system

      - name: Dvc setup
        run: |
          dvc remote modify --local minio access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local minio secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          TODO:
          git remote add experiments_adress https://oauth2:${{ env.REPO_TOKEN }}<http address of remote repository>

      - name: Create branch
        run: |
          dvc exp pull experiments_adress "${{ github.event.inputs.experiment_name }}"
          dvc exp branch "${{ github.event.inputs.experiment_name }}" "${{ github.event.inputs.experiment_name }}"
          git checkout "${{ github.event.inputs.experiment_name }}"

      - name: Pull raw data
        run: |
          dvc pull lab/data/raw --recursive

      - name: Reproduce Experiment ${{ github.event.inputs.experiment_name }}
        run: |
          dvc repro --pull

      - name: Create Pull Request
        run: |
          cml pr create --targetBranch=main
