name: experiments
on:
  push:
    tags:
      - "run-example*"
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  PYTHONPATH: ${{ github.workspace }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MLFLOW_S3_ENDPOINT_URL: https://minio.kdl-dell.konstellation.io
  TODO: Change bucket name
  MLFLOW_URL: https://<bucket-name>-mlflow.kdl-dell.konstellation.io
  GIT_TAG: ${{ github.ref_name }}
jobs:
  train-and-report:
    runs-on: ["igz", "dell", "cpu"]
    container:
      image: konstellation/kdl-py:3.9-cuda11.6-cudnn8-1.4.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Pipenv setup
        run: |
          pipenv sync --system

      - name: GIT setup
        run: |
          git config --global user.name "Continuous Development"
          git config --global user.email "oauth2@users.noreply.github.com"
          dvc remote modify --local minio access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local minio secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Pull raw data
        run: |
          dvc pull lab/data/raw --recursive

      - name: Run Experiment
        run: |
          dvc repro --pull

      - name: Share experiment
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw#*/}
          commit_message=$(git show -s --format=%B "origin/$branch")
          commit_message="${commit_message}-results"
          git add dvc.lock "**/**/.gitignore"
          git commit -m "$commit_message"
          git push origin "HEAD:$branch"
          dvc push
